//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvEntities : DbContext
    {
        public CvEntities()
            : base("name=CvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_adres> tbl_adres { get; set; }
        public virtual DbSet<tbl_Calismalarim> tbl_Calismalarim { get; set; }
        public virtual DbSet<tbl_hakkimda> tbl_hakkimda { get; set; }
        public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual DbSet<tbl_yetenekler> tbl_yetenekler { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
    }
}
